// Code generated by protoc-gen-go.
// source: proto/spider/spider.proto
// DO NOT EDIT!

/*
Package spider is a generated protocol buffer package.

It is generated from these files:
	proto/spider/spider.proto

It has these top-level messages:
	FetchDatasetRequest
	FetchDatasetResponse
	TrackSitemapRequest
	TrackSitemapResponse
	PrepareDatasetsRequest
	PrepareDatasetsResponse
*/
package spider

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FetchDatasetRequest struct {
	Id    uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	UrlId uint64 `protobuf:"varint,2,opt,name=url_id,json=urlId" json:"url_id,omitempty"`
}

func (m *FetchDatasetRequest) Reset()                    { *m = FetchDatasetRequest{} }
func (m *FetchDatasetRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchDatasetRequest) ProtoMessage()               {}
func (*FetchDatasetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type FetchDatasetResponse struct {
	Data map[string]string `protobuf:"bytes,1,rep,name=data" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *FetchDatasetResponse) Reset()                    { *m = FetchDatasetResponse{} }
func (m *FetchDatasetResponse) String() string            { return proto.CompactTextString(m) }
func (*FetchDatasetResponse) ProtoMessage()               {}
func (*FetchDatasetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FetchDatasetResponse) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

type TrackSitemapRequest struct {
	From     string            `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	Depth    uint64            `protobuf:"varint,2,opt,name=depth" json:"depth,omitempty"`
	Patterns map[string]string `protobuf:"bytes,3,rep,name=patterns" json:"patterns,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Name     string            `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
}

func (m *TrackSitemapRequest) Reset()                    { *m = TrackSitemapRequest{} }
func (m *TrackSitemapRequest) String() string            { return proto.CompactTextString(m) }
func (*TrackSitemapRequest) ProtoMessage()               {}
func (*TrackSitemapRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TrackSitemapRequest) GetPatterns() map[string]string {
	if m != nil {
		return m.Patterns
	}
	return nil
}

type TrackSitemapResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *TrackSitemapResponse) Reset()                    { *m = TrackSitemapResponse{} }
func (m *TrackSitemapResponse) String() string            { return proto.CompactTextString(m) }
func (*TrackSitemapResponse) ProtoMessage()               {}
func (*TrackSitemapResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type PrepareDatasetsRequest struct {
	SelectorId uint64   `protobuf:"varint,1,opt,name=selector_id,json=selectorId" json:"selector_id,omitempty"`
	Group      string   `protobuf:"bytes,2,opt,name=group" json:"group,omitempty"`
	Conditions []string `protobuf:"bytes,3,rep,name=conditions" json:"conditions,omitempty"`
}

func (m *PrepareDatasetsRequest) Reset()                    { *m = PrepareDatasetsRequest{} }
func (m *PrepareDatasetsRequest) String() string            { return proto.CompactTextString(m) }
func (*PrepareDatasetsRequest) ProtoMessage()               {}
func (*PrepareDatasetsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type PrepareDatasetsResponse struct {
	Count uint64 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
}

func (m *PrepareDatasetsResponse) Reset()                    { *m = PrepareDatasetsResponse{} }
func (m *PrepareDatasetsResponse) String() string            { return proto.CompactTextString(m) }
func (*PrepareDatasetsResponse) ProtoMessage()               {}
func (*PrepareDatasetsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*FetchDatasetRequest)(nil), "FetchDatasetRequest")
	proto.RegisterType((*FetchDatasetResponse)(nil), "FetchDatasetResponse")
	proto.RegisterType((*TrackSitemapRequest)(nil), "TrackSitemapRequest")
	proto.RegisterType((*TrackSitemapResponse)(nil), "TrackSitemapResponse")
	proto.RegisterType((*PrepareDatasetsRequest)(nil), "PrepareDatasetsRequest")
	proto.RegisterType((*PrepareDatasetsResponse)(nil), "PrepareDatasetsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Spider service

type SpiderClient interface {
	TrackSitemap(ctx context.Context, in *TrackSitemapRequest, opts ...client.CallOption) (*TrackSitemapResponse, error)
	FetchDataset(ctx context.Context, in *FetchDatasetRequest, opts ...client.CallOption) (*FetchDatasetResponse, error)
	PrepareDatasets(ctx context.Context, in *PrepareDatasetsRequest, opts ...client.CallOption) (*PrepareDatasetsResponse, error)
}

type spiderClient struct {
	c           client.Client
	serviceName string
}

func NewSpiderClient(serviceName string, c client.Client) SpiderClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "spider"
	}
	return &spiderClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *spiderClient) TrackSitemap(ctx context.Context, in *TrackSitemapRequest, opts ...client.CallOption) (*TrackSitemapResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Spider.TrackSitemap", in)
	out := new(TrackSitemapResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiderClient) FetchDataset(ctx context.Context, in *FetchDatasetRequest, opts ...client.CallOption) (*FetchDatasetResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Spider.FetchDataset", in)
	out := new(FetchDatasetResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiderClient) PrepareDatasets(ctx context.Context, in *PrepareDatasetsRequest, opts ...client.CallOption) (*PrepareDatasetsResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Spider.PrepareDatasets", in)
	out := new(PrepareDatasetsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Spider service

type SpiderHandler interface {
	TrackSitemap(context.Context, *TrackSitemapRequest, *TrackSitemapResponse) error
	FetchDataset(context.Context, *FetchDatasetRequest, *FetchDatasetResponse) error
	PrepareDatasets(context.Context, *PrepareDatasetsRequest, *PrepareDatasetsResponse) error
}

func RegisterSpiderHandler(s server.Server, hdlr SpiderHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Spider{hdlr}, opts...))
}

type Spider struct {
	SpiderHandler
}

func (h *Spider) TrackSitemap(ctx context.Context, in *TrackSitemapRequest, out *TrackSitemapResponse) error {
	return h.SpiderHandler.TrackSitemap(ctx, in, out)
}

func (h *Spider) FetchDataset(ctx context.Context, in *FetchDatasetRequest, out *FetchDatasetResponse) error {
	return h.SpiderHandler.FetchDataset(ctx, in, out)
}

func (h *Spider) PrepareDatasets(ctx context.Context, in *PrepareDatasetsRequest, out *PrepareDatasetsResponse) error {
	return h.SpiderHandler.PrepareDatasets(ctx, in, out)
}

func init() { proto.RegisterFile("proto/spider/spider.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 408 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x53, 0x4b, 0x8f, 0xd3, 0x30,
	0x10, 0x6e, 0xd2, 0xb4, 0x22, 0xb3, 0xbc, 0xe4, 0x4d, 0xd9, 0x90, 0x03, 0xbb, 0xf2, 0x01, 0xed,
	0xc9, 0x2b, 0xed, 0x1e, 0x40, 0xbc, 0x4e, 0xb0, 0x52, 0x6f, 0x55, 0xca, 0xbd, 0x32, 0xf1, 0x40,
	0xa3, 0xa6, 0xb1, 0xb1, 0x1d, 0xa4, 0xde, 0xf9, 0x7d, 0x88, 0x9f, 0x84, 0xe2, 0x38, 0x55, 0x5b,
	0xc2, 0x81, 0x53, 0x66, 0x46, 0x33, 0xf3, 0x3d, 0x32, 0x86, 0xe7, 0x4a, 0x4b, 0x2b, 0x6f, 0x8c,
	0x2a, 0x05, 0x6a, 0xff, 0x61, 0xae, 0x46, 0xdf, 0xc1, 0xf9, 0x3d, 0xda, 0x62, 0xfd, 0x91, 0x5b,
	0x6e, 0xd0, 0xe6, 0xf8, 0xbd, 0x41, 0x63, 0xc9, 0x63, 0x08, 0x4b, 0x91, 0x06, 0x57, 0xc1, 0x75,
	0x94, 0x87, 0xa5, 0x20, 0x33, 0x98, 0x36, 0xba, 0x5a, 0x95, 0x22, 0x0d, 0x5d, 0x6d, 0xd2, 0xe8,
	0x6a, 0x2e, 0xe8, 0xcf, 0x00, 0x92, 0xe3, 0x71, 0xa3, 0x64, 0x6d, 0x90, 0xdc, 0x41, 0x24, 0xb8,
	0xe5, 0x69, 0x70, 0x35, 0xbe, 0x3e, 0xbb, 0xbd, 0x64, 0x43, 0x4d, 0xac, 0xcd, 0x3f, 0xd5, 0x56,
	0xef, 0x72, 0xd7, 0x9c, 0xbd, 0x82, 0x78, 0x5f, 0x22, 0x4f, 0x61, 0xbc, 0xc1, 0x9d, 0xa3, 0x10,
	0xe7, 0x6d, 0x48, 0x12, 0x98, 0xfc, 0xe0, 0x55, 0x83, 0x8e, 0x42, 0x9c, 0x77, 0xc9, 0x9b, 0xf0,
	0x75, 0x40, 0x7f, 0x07, 0x70, 0xfe, 0x59, 0xf3, 0x62, 0xb3, 0x2c, 0x2d, 0x6e, 0xb9, 0xea, 0x55,
	0x10, 0x88, 0xbe, 0x6a, 0xb9, 0xf5, 0x4b, 0x5c, 0xdc, 0x6e, 0x11, 0xa8, 0xec, 0xba, 0x17, 0xe2,
	0x12, 0xf2, 0x01, 0x1e, 0x28, 0x6e, 0x2d, 0xea, 0xda, 0xa4, 0x63, 0xc7, 0x99, 0xb2, 0x81, 0x8d,
	0x6c, 0xe1, 0x9b, 0x3a, 0xda, 0xfb, 0x99, 0x16, 0xa9, 0xe6, 0x5b, 0x4c, 0xa3, 0x0e, 0xa9, 0x8d,
	0xb3, 0xb7, 0xf0, 0xe8, 0xa8, 0xfd, 0xbf, 0x24, 0xbd, 0x84, 0xe4, 0x18, 0xdf, 0x1b, 0x7b, 0xf2,
	0x63, 0xa8, 0x84, 0x67, 0x0b, 0x8d, 0x8a, 0x6b, 0xf4, 0xee, 0x9a, 0x5e, 0xfc, 0x25, 0x9c, 0x19,
	0xac, 0xb0, 0xb0, 0x52, 0xaf, 0xf6, 0x23, 0xd0, 0x97, 0xe6, 0xa2, 0x05, 0xff, 0xa6, 0x65, 0xa3,
	0x7a, 0x70, 0x97, 0x90, 0x17, 0x00, 0x85, 0xac, 0x45, 0x69, 0x4b, 0xe9, 0xbd, 0x88, 0xf3, 0x83,
	0x0a, 0xbd, 0x81, 0x8b, 0xbf, 0x00, 0x3d, 0xb7, 0x04, 0x26, 0x85, 0x6c, 0x6a, 0xeb, 0xb1, 0xba,
	0xe4, 0xf6, 0x57, 0x00, 0xd3, 0xa5, 0x3b, 0x39, 0xf2, 0x1e, 0x1e, 0x1e, 0x8a, 0x22, 0xc9, 0x90,
	0xc7, 0xd9, 0x8c, 0x0d, 0x29, 0xa7, 0xa3, 0x76, 0xfc, 0xf0, 0x8e, 0x48, 0xc2, 0x06, 0x4e, 0x37,
	0x9b, 0x0d, 0x1e, 0x1b, 0x1d, 0x91, 0x7b, 0x78, 0x72, 0xc2, 0x9c, 0x5c, 0xb0, 0x61, 0xf3, 0xb2,
	0x94, 0xfd, 0x43, 0x24, 0x1d, 0x7d, 0x99, 0xba, 0x97, 0x73, 0xf7, 0x27, 0x00, 0x00, 0xff, 0xff,
	0xaf, 0x63, 0x81, 0xd6, 0x56, 0x03, 0x00, 0x00,
}
